### ISSUE TITLE
Query evaluation is missing

### ISSUE THREAD

**Issue by adamretter** [evolvedbinary/fusion-studio-extension#187]
The buttons for executing/evaluating a query seem to be missing...

We should also add some Cypress tests to prevent regressions here again.

<img width="1680" alt="Screenshot 2020-07-24 at 13 04 43" src="https://user-images.githubusercontent.com/1264057/88385262-4ee73400-cdae-11ea-8c4f-e7d22978fecf.png">

**Comment by adamretter** [comment]
This seems to have come back using the latest HEAD version - which I don't understand as @ccheraa added some Cypress tests for this. I see this error output in the "Developer Tools" console window:

```
root ERROR TypeError: console.originalConsoleLog is not a function
    at FSEvalWidget.push../node_modules/fusion-studio-extension/lib/browser/widget/eval.js.FSEvalWidget.render (file:///Users/aretter/tmp-code/evolvedbinary/fusion-studio-extension/electron-app/lib/17.bundle.js:31380:17)
    at FSEvalWidget.../node_modules/@theia/core/lib/browser/widgets/react-widget.js.ReactWidget.onUpdateRequest (file:///Users/aretter/tmp-code/evolvedbinary/fusion-studio-extension/electron-app/lib/bundle.js:56503:72)
    at FSEvalWidget.../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (file:///Users/aretter/tmp-code/evolvedbinary/fusion-studio-extension/electron-app/lib/bundle.js:26328:22)
    at invokeHandler (file:///Users/aretter/tmp-code/evolvedbinary/fusion-studio-extension/electron-app/lib/bundle.js:10271:21)
    at sendMessage (file:///Users/aretter/tmp-code/evolvedbinary/fusion-studio-extension/electron-app/lib/bundle.js:10007:13)
    at runMessageLoop (file:///Users/aretter/tmp-code/evolvedbinary/fusion-studio-extension/electron-app/lib/bundle.js:10321:17)
```

**Comment by adamretter** [comment]
Nevermind... I had an outdated version of the API (updating to 0.2.0 fixes it) :-p
