### ISSUE TITLE
list of errorss reported by yarn dev server

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/fusion-studio-extension#509]
node 14, api 1.2, 

I repeatedly see both errors, haven't been able to tie them to a specific operation, but they seem to occur anytime i bring up the dev server
```log
root ERROR Child node 'open-editors:root' does not belong to this 'open-editors:root' tree.
```

this might explain our troubles with tree updating when an editor window is open.

```shell
root ERROR not caught: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
this is an upstream bug related to how node writes to the filesystem, see https://github.com/eclipse-theia/theia/issues/8384 .

**Comment by duncdrum** [comment]
part 2:

```shell
root ERROR Error during serialization of layout data TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'children' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'connectionNode' closes the circle
    at JSON.stringify (<anonymous>)
    at ShellLayoutRestorer.__webpack_modules__.../node_modules/@theia/core/lib/browser/shell/shell-layout-restorer.js.ShellLayoutRestorer.deflate (http://localhost:3000/bundle.js:52836:21)
    at ShellLayoutRestorer.__webpack_modules__.../node_modules/@theia/core/lib/browser/shell/shell-layout-restorer.js.ShellLayoutRestorer.convertToDescription (http://localhost:3000/bundle.js:52872:44)
    at Object.<anonymous> (http://localhost:3000/bundle.js:52839:41)
    at JSON.stringify (<anonymous>)
    at ShellLayoutRestorer.__webpack_modules__.../node_modules/@theia/core/lib/browser/shell/shell-layout-restorer.js.ShellLayoutRestorer.deflate (http://localhost:3000/bundle.js:52836:21)
    at ShellLayoutRestorer.__webpack_modules__.../node_modules/@theia/core/lib/browser/shell/shell-layout-restorer.js.ShellLayoutRestorer.storeLayout (http://localhost:3000/bundle.js:52789:49)
    at http://localhost:3000/bundle.js:40891:34
    at http://localhost:3000/bundle.js:67649:33
    at CallbackList.__webpack_modules__.../node_modules/@theia/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:67664:39)
```

```
root ERROR not caught: TypeError: Failed to fetch
```

```
root ERROR Error: [UriError]: Scheme contains illegal characters.
    at _validateUri (http://localhost:3000/bundle.js:148357:15)
    at _URI.URI (http://localhost:3000/bundle.js:148448:13)
    at new _URI (http://localhost:3000/bundle.js:148669:47)
    at Function.URI.parse (http://localhost:3000/bundle.js:148560:16)
    at ResourceContextKey.__webpack_modules__.../node_modules/@theia/core/lib/browser/resource-context-key.js.ResourceContextKey.set (http://localhost:3000/bundle.js:50037:66)
    at updateContextKeys (http://localhost:3000/bundle.js:36535:38)
    at http://localhost:3000/bundle.js:67649:33
    at CallbackList.__webpack_modules__.../node_modules/@theia/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:67664:39)
    at Emitter.__webpack_modules__.../node_modules/@theia/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:67791:29)
    at SelectionService.set (http://localhost:3000/bundle.js:72004:44)
```

```
root ERROR caught: { code: 0, data: [ {} ] }
```

**Comment by duncdrum** [comment]
Wrong commit message. My mistake.  these errors still need investigating.
