### ISSUE TITLE
unhandled exception on creation of new file revealed by test

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/fusion-studio-extension#517]
```
cypress_runner.js:190952 Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Unable to resolve filesystem provider with relative file path admin@http://localhost:8080/db/untitled-1

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at new FileOperationError (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:2866:28)
    at FileService.<anonymous> (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:358:27)
    at step (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:121:23)
    at Object.next (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:102:53)
    at http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:96:71
    at new Promise (<anonymous>)
    at push.../node_modules/@theia/filesystem/lib/browser/file-service.js.__awaiter (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:92:12)
    at FileService.push.../node_modules/@theia/filesystem/lib/browser/file-service.js.FileService.withProvider (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:354:16)
    at FileService.<anonymous> (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:423:55)
    at step (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-service_js.bundle.js:121:23)
From previous event:
    at Object.run (http://localhost:3000/__cypress/runner/cypress_runner.js:182785:23)
    at Object.run (http://localhost:3000/__cypress/runner/cypress_runner.js:168703:17)
    at $Cy.cy.<computed> [as get] (http://localhost:3000/__cypress/runner/cypress_runner.js:169873:19)
    at __stackReplacementMarker (http://localhost:3000/__cypress/runner/cypress_runner.js:169181:13)
    at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:170097:23)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:122959:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:122946:7)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:176627:30
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:176612:19)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:166178:28)
    at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:174346:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:123618:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:123744:12
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:123527:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:123537:7
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:123439:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:123505:5
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:117431:27)
```

**Comment by duncdrum** [comment]
same issue different error `undefined: undefined`

```
Event:      uncaught exception
Caught by:  "unhandledrejection" handler
Error:      node already exists
```

stack:
```
CypressError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > 

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > 

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at Object.run (http://localhost:3000/__cypress/runner/cypress_runner.js:182785:23)
    at Object.run (http://localhost:3000/__cypress/runner/cypress_runner.js:168703:17)
    at $Cy.cy.<computed> [as get] (http://localhost:3000/__cypress/runner/cypress_runner.js:169873:19)
    at __stackReplacementMarker (http://localhost:3000/__cypress/runner/cypress_runner.js:169181:13)
    at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:170097:23)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:122959:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:122946:7)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:176627:30
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:176612:19)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:166178:28)
    at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:174346:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:123618:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:123744:12
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:123527:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:123537:7
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:123439:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:123505:5
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:117431:27)
logError @ cypress_runner.js:190952
(anonymous) @ cypress_runner.js:189393
emit @ cypress_runner.js:21361
(anonymous) @ cypress_runner.js:186038
emit @ cypress_runner.js:21361
emit @ cypress_runner.js:186099
onPrint @ cypress_runner.js:184928
_onPrintClick @ cypress_runner.js:184933
(anonymous) @ cypress_runner.js:186270
executeAction @ cypress_runner.js:66297
n @ cypress_runner.js:66297
ca @ cypress_runner.js:76382
ja @ cypress_runner.js:76383
ka @ cypress_runner.js:76383
wa @ cypress_runner.js:76385
Aa @ cypress_runner.js:76386
ya @ cypress_runner.js:76386
Da @ cypress_runner.js:76389
Ad @ cypress_runner.js:76452
Gi @ cypress_runner.js:76618
Kb @ cypress_runner.js:76407
Dd @ cypress_runner.js:76454
(anonymous) @ cypress_runner.js:76619
../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ cypress_runner.js:81207
Ii @ cypress_runner.js:76619
Cd @ cypress_runner.js:76453
```
